
# $grep  '[0-9])$' Libro\ de\ residencias.txt | uniq
PROVINCIAS = [('BUENOS AIRES', 06),
              ('CATAMARCA', 10),
              ('CORDOBA', 14),
              ('CORRIENTES', 18),
              ('CHACO', 22),
              ('CHUBUT', 26),
              ('ENTRE RIOS', 30),
              ('FORMOSA', 34),
              ('JUJUY', 38),
              ('LA PAMPA', 42),
              ('LA RIOJA', 46),
              ('MENDOZA', 50),
              ('MISIONES', 54),
              ('NEUQUEN', 58),
              ('RIO NEGRO', 62),
              ('SALTA', 66),
              ('SAN JUAN', 70),
              ('SAN LUIS', 74),
              ('SANTA CRUZ', 78),
              ('SANTA FE', 82),
              ('SANTIAGO DEL ESTERO', 86),
              ('TIERRA DEL FUEGO', 94),
              ('TUCUMAN', 90)]
