# -*- encoding: utf-8 -*-

# $grep  '[0-9])$' Libro\ de\ residencias.txt | uniq
PROVINCIAS = [('BUENOS AIRES', 6),
              ('CATAMARCA', 10),
              ('CORDOBA', 14),
              ('CORRIENTES', 18),
              ('CHACO', 22),
              ('CHUBUT', 26),
              ('ENTRE RIOS', 30),
              ('FORMOSA', 34),
              ('JUJUY', 38),
              ('LA PAMPA', 42),
              ('LA RIOJA', 46),
              ('MENDOZA', 50),
              ('MISIONES', 54),
              ('NEUQUEN', 58),
              ('RIO NEGRO', 62),
              ('SALTA', 66),
              ('SAN JUAN', 70),
              ('SAN LUIS', 74),
              ('SANTA CRUZ', 78),
              ('SANTA FE', 82),
              ('SANTIAGO DEL ESTERO', 86),
              ('TIERRA DEL FUEGO', 94),
              ('TUCUMAN', 90)]

BARRIOS = [(2, u'Agronomía'),
           (3, u'Almagro'),
           (4, u'Balvanera'),
           (5, u'Barracas'),
           (6, u'Belgrano'),
           (7, u'Boedo'),
           (8, u'Caballito'),
           (9, u'Chacarita'),
           (10, u'Coghlan'),
           (11, u'Colegiales'),
           (12, u'Flores'),
           (13, u'Floresta'),
           (14, u'La Boca'),
           (15, u'Liniers'),
           (16, u'Mataderos'),
           (17, u'Monserrat'),
           (18, u'Monte Castro'),
           (19, u'Nueva Pompeya'),
           (20, u'Nuñez'),
           (21, u'Palermo'),
           (22, u'Parque Avellaneda'),
           (23, u'Parque Chacabuco'),
           (24, u'Parque Chas'),
           (25, u'Parque Patricios'),
           (26, u'Paternal'),
           (27, u'Puerto Madero'),
           (28, u'Recoleta'),
           (29, u'Retiro'),
           (30, u'Saavedra'),
           (31, u'San Cristobal'),
           (32, u'San Nicolás'),
           (33, u'San Telmo'),
           (34, u'Velez Sarsfield'),
           (35, u'Versalles'),
           (36, u'Villa Crespo'),
           (37, u'Villa del Parque'),
           (38, u'Villa Devoto'),
           (39, u'Villa General Mitre'),
           (40, u'Villa Lugano'),
           (41, u'Villa Luro'),
           (42, u'Villa Ortuzar'),
           (43, u'Villa Pueyrredón'),
           (44, u'Villa Real'),
           (45, u'Villa Riachuelo'),
           (46, u'Villa Santa Rita'),
           (47, u'Villa Soldati'),
           (48, u'Villa Urquiza')]
